const LANG = {
  KR: {
    // 로그인/회원가입
    'login': '로그인',
    'signup': '회원가입',
    'email': '이메일',
    'password': '비밀번호',
    'password_confirm': '비밀번호 확인',
    'no_account': '계정이 없으신가요?',
    'has_account': '이미 계정이 있으신가요?',
    'continue_google': 'Google로 시작하기',
    'continue_kakao': '카카오로 시작하기',
    'continue_local': '로그인 없이 계속 (로컬 모드)',
    'agree_start': '동의하고 시작하기',
    'terms_title': '서비스 이용 동의',
    'terms_required': '[필수] 이용약관 동의',
    'privacy_required': '[필수] 개인정보 처리방침',
    'age_required': '[필수] 만 14세 이상입니다',
    'risk_required': '[필수] 투자 리스크를 이해합니다',
    'marketing_optional': '[선택] 마케팅 정보 수신 동의',
    'agree_all': '전체 동의',
    'view': '보기',
    // 네비게이션
    'nav_home': '홈',
    'nav_screener': '종목검색',
    'nav_strategy': '전략설정',
    'nav_tradingview': '트레이딩뷰 연결',
    'nav_premium': '프리미엄 전략',
    'nav_market': '시장분석',
    'nav_kr_market': '국내시장',
    'nav_us_market': '해외시장',
    'nav_etf': 'ETF',
    'nav_crypto': '코인',
    'nav_watchlist': '관심종목',
    'nav_settings': '설정',
    'nav_account': '계정관리',
    'nav_notification': '알림설정',
    'nav_appinfo': '앱정보',
    'nav_admin': '관리자',
    'nav_user_mgmt': '사용자관리',
    'nav_system': '시스템상태',
    'nav_logout': '로그아웃',
    // 홈 대시보드
    'total_assets': '총 자산',
    'total_return': '총 수익률',
    'daily_change': '일간 변동',
    'asset_allocation': '자산 배분',
    'holdings': '보유 자산',
    'active_strategies': '활성 전략',
    'recent_trades': '최근 거래 내역',
    'refresh': '새로고침',
    'load_more': '더보기',
    'all_exchanges': '전체 거래소',
    'connect_account': '계정 연결하기',
    'no_account_connected': '연결된 계정이 없습니다.',
    'add_strategy': '전략 추가하기',
    'no_active_strategy': '활성 전략이 없습니다.',
    'no_trade_history': '거래 내역이 없습니다.',
    // 테이블 헤더
    'asset': '자산명',
    'exchange': '거래소',
    'quantity': '보유수량',
    'avg_price': '평균단가',
    'current_price': '현재가',
    'value': '평가액',
    'pnl': '평가손익',
    'return': '수익률',
    'symbol': '종목',
    'side': '구분',
    'qty': '수량',
    'price': '가격',
    'status': '상태',
    'time': '시간',
    'action': '액션',
    'strategy': '전략명',
    // 전략 설정
    'step1': '단계 1. 거래소 선택',
    'step2': '단계 2. 자산 선택',
    'step3': '단계 3. 매매 설정',
    'step4': '단계 4. 템플릿 확인',
    'select_exchange': '거래소 선택',
    'select_asset': '자산 선택',
    'trading_settings': '매매 설정',
    'confirm_template': '템플릿 확인',
    'back': '이전',
    'next': '다음',
    'copy': '복사',
    'start_over': '처음부터 다시',
    'generate_template': '템플릿 생성',
    'run_backtest': '백테스트 실행',
    'sizing': '사이징 (Sizing)',
    'risk': '리스크 (Risk)',
    'limits': '리밋 (Limits)',
    'stop_loss': '손절 (SL) 활성화',
    'take_profit': '익절 (TP) 활성화',
    'trailing_stop': '트레일링 스탑 활성화',
    'webhook_url': '웹훅 URL',
    'json_template': 'JSON 템플릿',
    'recent_webhooks': '최근 수신 웹훅',
    // 공통 상태
    'loading': '로딩 중...',
    'saving': '저장 중...',
    'testing': '테스트 중...',
    'analyzing': '분석 중...',
    'preparing': '준비 중...',
    'generating': '생성 중...',
    'no_results': '검색 결과가 없습니다',
    'load_failed': '조회 실패',
    'search_failed': '검색 실패',
    'connecting': '서버 연결 중...',
    'connected': '서버: 연결됨',
    'offline': '서버: 오프라인',
    'retrying': '연결 재시도 중...',
    'cannot_connect': '서버에 연결할 수 없습니다.\n네트워크를 확인해주세요.',
    'test_connection': '연결 테스트',
    'connection_failed': '연결 실패',
    'pdf_download': 'PDF 다운로드',
    'last_updated': '마지막 업데이트:',
    'total': '합계',
    'results': '결과',
    'emergency_stop': '긴급 정지 - 모든 자동매매 즉시 중단',
  },
  EN: {
    // 로그인/회원가입
    'login': 'Sign In',
    'signup': 'Sign Up',
    'email': 'Email',
    'password': 'Password',
    'password_confirm': 'Confirm Password',
    'no_account': "Don't have an account?",
    'has_account': 'Already have an account?',
    'continue_google': 'Continue with Google',
    'continue_kakao': 'Continue with Kakao',
    'continue_local': 'Continue without login (Local mode)',
    'agree_start': 'Agree and Continue',
    'terms_title': 'Terms of Service Agreement',
    'terms_required': '[Required] Terms of Service',
    'privacy_required': '[Required] Privacy Policy',
    'age_required': '[Required] I am 14 years or older',
    'risk_required': '[Required] I understand investment risks',
    'marketing_optional': '[Optional] Marketing communications',
    'agree_all': 'Agree to All',
    'view': 'View',
    // 네비게이션
    'nav_home': 'Home',
    'nav_screener': 'Stock Screener',
    'nav_strategy': 'Strategy',
    'nav_tradingview': 'TradingView Connect',
    'nav_premium': 'Premium Strategy',
    'nav_market': 'Market Analysis',
    'nav_kr_market': 'KR Market',
    'nav_us_market': 'US Market',
    'nav_etf': 'ETF',
    'nav_crypto': 'Crypto',
    'nav_watchlist': 'Watchlist',
    'nav_settings': 'Settings',
    'nav_account': 'Account Management',
    'nav_notification': 'Notifications',
    'nav_appinfo': 'App Info',
    'nav_admin': 'Admin',
    'nav_user_mgmt': 'User Management',
    'nav_system': 'System Status',
    'nav_logout': 'Sign Out',
    // 홈 대시보드
    'total_assets': 'Total Assets',
    'total_return': 'Total Return',
    'daily_change': 'Daily Change',
    'asset_allocation': 'Asset Allocation',
    'holdings': 'Holdings',
    'active_strategies': 'Active Strategies',
    'recent_trades': 'Recent Trades',
    'refresh': 'Refresh',
    'load_more': 'Load More',
    'all_exchanges': 'All Exchanges',
    'connect_account': 'Connect Account',
    'no_account_connected': 'No connected accounts.',
    'add_strategy': 'Add Strategy',
    'no_active_strategy': 'No active strategies.',
    'no_trade_history': 'No trade history.',
    // 테이블 헤더
    'asset': 'Asset',
    'exchange': 'Exchange',
    'quantity': 'Quantity',
    'avg_price': 'Avg Price',
    'current_price': 'Current Price',
    'value': 'Value',
    'pnl': 'P&L',
    'return': 'Return',
    'symbol': 'Symbol',
    'side': 'Side',
    'qty': 'Qty',
    'price': 'Price',
    'status': 'Status',
    'time': 'Time',
    'action': 'Action',
    'strategy': 'Strategy',
    // 전략 설정
    'step1': 'Step 1. Select Exchange',
    'step2': 'Step 2. Select Asset',
    'step3': 'Step 3. Trading Settings',
    'step4': 'Step 4. Confirm Template',
    'select_exchange': 'Select Exchange',
    'select_asset': 'Select Asset',
    'trading_settings': 'Trading Settings',
    'confirm_template': 'Confirm Template',
    'back': 'Back',
    'next': 'Next',
    'copy': 'Copy',
    'start_over': 'Start Over',
    'generate_template': 'Generate Template',
    'run_backtest': 'Run Backtest',
    'sizing': 'Sizing',
    'risk': 'Risk',
    'limits': 'Limits',
    'stop_loss': 'Enable Stop Loss',
    'take_profit': 'Enable Take Profit',
    'trailing_stop': 'Enable Trailing Stop',
    'webhook_url': 'Webhook URL',
    'json_template': 'JSON Template',
    'recent_webhooks': 'Recent Webhooks',
    // 공통 상태
    'loading': 'Loading...',
    'saving': 'Saving...',
    'testing': 'Testing...',
    'analyzing': 'Analyzing...',
    'preparing': 'Preparing...',
    'generating': 'Generating...',
    'no_results': 'No results found',
    'load_failed': 'Failed to load',
    'search_failed': 'Search failed',
    'connecting': 'Connecting to server...',
    'connected': 'Server: Connected',
    'offline': 'Server: Offline',
    'retrying': 'Retrying connection...',
    'cannot_connect': 'Unable to connect to server.\nPlease check your network.',
    'test_connection': 'Test Connection',
    'connection_failed': 'Connection Failed',
    'pdf_download': 'Download PDF',
    'last_updated': 'Last updated:',
    'total': 'Total',
    'results': 'Results',
    'emergency_stop': 'Emergency Stop - Stop all strategies immediately',
  }
};

// 번역 함수
function t(key) {
  const mode = (typeof getAppMode === 'function' ? getAppMode() : 'KR');
  const lang = mode === 'US' ? 'EN' : 'KR';
  return LANG[lang][key] || LANG['KR'][key] || key;
}

// 전체 페이지 텍스트 교체 함수
function applyTranslations() {
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    const attr = el.getAttribute('data-i18n-attr'); // placeholder 등 속성용
    if (attr) {
      el.setAttribute(attr, t(key));
    } else {
      el.textContent = t(key);
    }
  });
}

export { LANG, t, applyTranslations };
